{
 "title": "Ojo NFS Client",
 "tags": [
  "ojo",
  "nfs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(system_nfs_client_source_available, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(system_nfs_client_source_available{job=~\"$service\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Source Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(system_nfs_client_source_available{job=~\"$service\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "NFS Mounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "max(system_nfs_client_mounts{job=~\"$service\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "RPC Calls / Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(system_nfs_client_rpc_calls_rate_per_second{job=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "RPC Calls/s"
    }
   ]
  },
  {
   "title": "RPC Retransmissions / Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(system_nfs_client_rpc_retransmissions_rate_per_second{job=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "Retransmissions/s"
    }
   ]
  },
  {
   "title": "RPC Counters (Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(system_nfs_client_rpc_calls_total{job=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "Calls"
    },
    {
     "expr": "sum(system_nfs_client_rpc_retransmissions_total{job=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "Retransmissions"
    },
    {
     "expr": "sum(system_nfs_client_rpc_auth_refreshes_total{job=~\"$service\",instance=~\"$instance\"})",
     "legendFormat": "Auth Refreshes"
    }
   ]
  }
 ]
}