pub(crate) fn collect_snapshot() -> crate::SystraceSnapshot {
    crate::SystraceSnapshot {
        available: true,
        tracefs_available: true,
        etw_available: false,
        tracing_on: true,
        current_tracer: "function_graph".to_string(),
        tracers_available: 4,
        events_total: 120,
        events_enabled: 9,
        buffer_total_kb: 4096,
        etw_sessions_total: 0,
        etw_sessions_running: 0,
        etw_providers_total: 0,
        event_categories_total: 12,
        trace_sample_lines_total: 0,
        trace_sample: Vec::new(),
        context_switches_per_sec: 3000.0,
        interrupts_per_sec: 500.0,
        system_calls_per_sec: 12000.0,
        system_calls_source: "linux_vmstat_nr_syscalls".to_string(),
        system_calls_source_code: 1,
        system_calls_coverage_ratio: 1.0,
        dpcs_per_sec: 50.0,
        process_forks_per_sec: 4.0,
        run_queue_depth: 2.0,
        processes_total: 420,
        threads_total: 2600,
        kernel_stack_samples_total: 12,
        user_stack_samples_total: 3,
        collection_errors: 0,
    }
}
